#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'descifrar.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from baconcoding import BaconEncoding


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 635)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 781, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 341, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.inputMensajeOriginal = QtWidgets.QTextBrowser(self.tab)
        self.inputMensajeOriginal.setGeometry(QtCore.QRect(10, 40, 761, 71))
        self.inputMensajeOriginal.setReadOnly(False)
        self.inputMensajeOriginal.setObjectName("inputMensajeOriginal")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.inputMensajeFalso = QtWidgets.QTextBrowser(self.tab)
        self.inputMensajeFalso.setGeometry(QtCore.QRect(10, 180, 761, 61))
        self.inputMensajeFalso.setReadOnly(False)
        self.inputMensajeFalso.setObjectName("inputMensajeFalso")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 331, 17))
        self.label_5.setObjectName("label_5")
        self.caractercount = QtWidgets.QLabel(self.tab)
        self.caractercount.setGeometry(QtCore.QRect(240, 250, 181, 17))
        self.caractercount.setText("")
        self.caractercount.setObjectName("caractercount")
        self.outputMensajeCifrado = QtWidgets.QTextEdit(self.tab)
        self.outputMensajeCifrado.setGeometry(QtCore.QRect(10, 350, 761, 70))
        self.outputMensajeCifrado.setObjectName("outputMensajeCifrado")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 330, 171, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ErrorLabel = QtWidgets.QLabel(self.tab)
        self.ErrorLabel.setEnabled(True)
        self.ErrorLabel.setGeometry(QtCore.QRect(130, 290, 461, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ErrorLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.inputTextoDescifrar = QtWidgets.QTextEdit(self.tab_2)
        self.inputTextoDescifrar.setGeometry(QtCore.QRect(10, 100, 761, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputTextoDescifrar.setFont(font)
        self.inputTextoDescifrar.setObjectName("inputTextoDescifrar")
        self.outputTextoDescifrar = QtWidgets.QTextEdit(self.tab_2)
        self.outputTextoDescifrar.setGeometry(QtCore.QRect(10, 270, 761, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.outputTextoDescifrar.setFont(font)
        self.outputTextoDescifrar.setReadOnly(True)
        self.outputTextoDescifrar.setObjectName("outputTextoDescifrar")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 287, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 371, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.baconapi = BaconEncoding()
        self.ErrorLabel.hide()
        self.connectActions()

    def connectActions(self):
        self.inputTextoDescifrar.textChanged.connect(self.show_texto_descifrado)
        self.inputMensajeOriginal.textChanged.connect(self.updateCharcount)
        self.inputMensajeFalso.textChanged.connect(self.updateCharcount)
        self.inputMensajeFalso.textChanged.connect(self.show_texto_cifrado)

    def show_texto_descifrado(self):
        cifrado = self.inputTextoDescifrar.toPlainText()
        descifrado = self.baconapi.decodificaBacon(cifrado)
        self.outputTextoDescifrar.setText(descifrado)

    def show_texto_cifrado(self):
        originaltext = self.inputMensajeOriginal.toPlainText()
        faketext = self.inputMensajeFalso.toPlainText()
        codificado = self.baconapi.codificaBacon(originaltext, faketext)
        self.outputMensajeCifrado.setText(codificado)

    def updateCharcount(self):
        lorigin = len(self.baconapi.phase1(self.inputMensajeOriginal.toPlainText()))
        lfake = self.baconapi.alphalen(self.inputMensajeFalso.toPlainText())
        self.caractercount.setText(str(lfake) + "/" + str(lorigin))
        if lfake > lorigin:
            self.ErrorLabel.show()
        else:
            self.ErrorLabel.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CifradoBacon"))
        self.label.setText(_translate("MainWindow", "GUI para Cifrado Bacon"))
        self.label_3.setText(_translate("MainWindow", "Introduce el mensaje original:"))
        self.label_4.setText(_translate("MainWindow", "Mensaje falso:"))
        self.label_5.setText(_translate("MainWindow", "Su mensaje falso debe contener:"))
        self.label_6.setText(_translate("MainWindow", "Mensaje Cifrado:"))
        self.ErrorLabel.setText(_translate("MainWindow", "Warning: tu mensaje es demasiado largo, no se usará por completo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cifrar"))
        self.label_2.setText(_translate("MainWindow", "Introduce el mensaje cifrado:"))
        self.label_7.setText(_translate("MainWindow", "Mensaje original:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Descifrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

